### ISSUE TITLE
New FT NED Logo

### ISSUE THREAD

**Issue by coyac** [Financial-Times/origami-specialist-title-logos#16]
## What

NED (https://non-execs.ft.com) is changing its brand on the 8th of July. Can you please change their website logo (new SVG logo attached).
Many thanks 

[FT_NED_BOARD DIRECTOR PROGRAMME_REV_RGB (1).svg.zip](https://github.com/Financial-Times/origami-specialist-title-logos/files/3301412/FT_NED_BOARD.DIRECTOR.PROGRAMME_REV_RGB.1.svg.zip)

**Comment by alexwilson** [comment]
Closed by #17
